# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: gcc

test:
  script:
    - echo "Installing vfgen"
    - apt-get -y update && apt-get -y install cmake libmxml-dev libginac-dev
    - cd cmake_build
    - cmake ../src
    - make
    - make install
    - cd ..
    - echo "Installing octave"
    - apt-get -y install octave
    - echo "Testing help"
    - vfgen help help
    - cd tests
    - echo "Testing octave"
    - cd test_octave
    - vfgen octave ../vf/linearosc.vf
    - octave --no-gui --no-window-system test_octave.m
    - cd ..
    - echo "Testing lsoda"
    - cd test_lsoda
    - bash run_test.sh
    - cd ..

  #
  #artifacts:
  #  paths:
  #    - cmake_build/vfgen
  #
  # depending on your build setup it's most likely a good idea to cache outputs
  # to reduce the build time
  # cache:
  #   paths:
  #     - "*.o"

# run tests using the binary built before
# (This doesn't work--the binary probably needs to be saved somewhere.)
#test:
#  stage: test
#  script:
#    - cd cmake_build
#    - ./vfgen help
