# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: gcc

before_script:
  - apt update && apt -y install cmake libmxml-dev libginac-dev

test_octave:
  script:
    - apt -y install octave
    - cd cmake_build
    - cmake ../src
    - make
    - make install
    - cd ../tests/test_octave
    - vfgen octave linearosc.vf
    - octave --no-gui --no-window-system test_octave.m

test_help:
  script:
    - cd cmake_build
    - cmake ../src
    - make
    - make install
    - vfgen help help

  #
  #artifacts:
  #  paths:
  #    - cmake_build/vfgen
  #
  # depending on your build setup it's most likely a good idea to cache outputs
  # to reduce the build time
  # cache:
  #   paths:
  #     - "*.o"

# run tests using the binary built before
# (This doesn't work--the binary probably needs to be saved somewhere.)
#test:
#  stage: test
#  script:
#    - cd cmake_build
#    - ./vfgen help
