rm -f aclocal.m4
rm -rf autom4te.cache
rm -f Makefile
rm -f config.h
rm -f confdefs.h
rm -f config.h.in
rm -f config.log
rm -f config.status
rm -f configure
rm -f depcomp
rm -f INSTALL
rm -f install-sh
rm -f Makefile
rm -f Makefile.in
rm -f missing
rm -f stamp-h1
rm -f src/Makefile
rm -f src/Makefile.in
