#
# linearosc.m
#
# Octave vector field functions for: linearosc
#
# This file was generated by the program VFGEN, version: 2.6.0.dev0
# Generated on 20-May-2019 at 14:55
#

# The next line, containing just the number 1, is not a mistake!
# It allows the file to define more than one function.
1;

#
# linearosc_vf
#
# The vector field 
#
function vf_ = linearosc_vf(x_, t)
    x          = x_(1);
    y          = x_(2);
    vf_ = zeros(2, 1);
    vf_(1) = -y;
    vf_(2) = x;
endfunction

#
# linearosc_jac
#
# The Jacobian of the vector field
#
function jac_ = linearosc_jac(x_, t)
    x          = x_(1);
    y          = x_(2);
    jac_ = zeros(2, 2);
    jac_(1, 2) = -1;
    jac_(2, 1) = 1;
endfunction

