name: Test commands

on: [push, pull_request]

jobs:
  test_vfgen:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install
      run: |
        sudo apt-get -y update && sudo apt-get -y install lsb-release
        lsb_release -irc
        echo "Installing vfgen"
        sudo apt-get -y install cmake libmxml-dev libginac-dev
        cd cmake_build
        cmake ../src
        make
        make install
        cd ..
    - name: test_boostodeint
      if: "contains(github.event.head_commit.message, '[test all]') || contains(github.event.head_commit.message, '[test boostodeint]')"
      run: |
        cd tests/test_boostodeint
        run_test_boostodeint_default_noparams.sh
        run_test_boostodeint_default_params.sh
        run_test_boostodeint_implicit_noparams.sh
        run_test_boostodeint_implicit_params.sh
        cd ../..
    - name: test_dde_solver
      if: "contains(github.event.head_commit.message, '[test all]') || contains(github.event.head_commit.message, '[test dde_solver]')"
      run: |
        cd tests/test_dde_solver
        sudo bash run_test.sh
        cd ../..
    - name: test_evf
      if: "contains(github.event.head_commit.message, '[test all]') || contains(github.event.head_commit.message, '[test evf]')"
      run: |
        cd tests/test_evf
        sudo bash run_test.sh
        cd ../..
    - name: test_gsl
      if: "contains(github.event.head_commit.message, '[test all]') || contains(github.event.head_commit.message, '[test gsl]')"
      run: |
        cd tests/test_gsl
        sudo bash run_test.sh
        cd ../..
    - name: test_help
      run: |
        vfgen help help
    - name: test_julia
      if: "contains(github.event.head_commit.message, '[test all]') || contains(github.event.head_commit.message, '[test julia]')"
      run: |
        cd tests/test_julia
        bash run_test.sh
        cd ../..
    - name: test_lsoda
      if: "contains(github.event.head_commit.message, '[test all]') || contains(github.event.head_commit.message, '[test lsoda]')"
      run: |
        cd tests/test_lsoda
        bash download_lsoda.sh
        bash run_test_linearosc.sh
        bash run_test_pidecay.sh
        cd ../..
    - name: test_octave
      if: "contains(github.event.head_commit.message, '[test all]') || contains(github.event.head_commit.message, '[test octave]')"
      run: |
        cd tests/test_octave
        sudo bash run_test.sh
        cd ../..
    - name: test_pygsl
      if: "contains(github.event.head_commit.message, '[test all]') || contains(github.event.head_commit.message, '[test pygsl]')"
      run: |
        cd tests/test_pygsl
        sudo bash run_test.sh
        cd ../..
    - name: test_r
      if: "contains(github.event.head_commit.message, '[test all]') || contains(github.event.head_commit.message, '[test r]')"
      uses: r-lib/actions/setup-r@v2
      run: |
        cd tests/test_r
        bash run_test.sh
        cd ../..
    - name: test_scilab
      if: "contains(github.event.head_commit.message, '[test all]') || contains(github.event.head_commit.message, '[test scilab]')"
      run: |
        cd tests/test_scilab
        sudo bash run_test.sh
        cd ..
    - name: test_scipy
      if: "contains(github.event.head_commit.message, '[test all]') || contains(github.event.head_commit.message, '[test scipy]')"
      run: |
        cd tests/test_scipy
        sudo bash run_test.sh
        cd ..
