name: Test commands

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: make and run
      run: |
        sudo apt-get -y update && sudo apt-get -y install lsb-release
        lsb_release -irc
        echo "Installing vfgen"
        sudo apt-get -y install cmake libmxml-dev libginac-dev
        cd cmake_build
        cmake ../src
        make
        make install
        cd ../tests
        sudo bash run_ci_tests.sh
